'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh';

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Common
    'app.title': 'Life Strategy AI',
    'app.subtitle': 'Strategic Intelligence for Life Decisions',
    
    // Identity Sync
    'identity.title': 'Life Strategy AI',
    'identity.subtitle': 'Strategic Intelligence for Critical Decisions',
    'identity.heading': 'Identity Sync',
    'identity.description': 'Your temporal coordinates unlock the strategic matrix',
    'identity.birthDate': 'Birth Date',
    'identity.birthTime': 'Birth Time',
    'identity.timezone': 'Timezone',
    'identity.timezone.pacific': 'UTC-8 (Pacific)',
    'identity.timezone.eastern': 'UTC-5 (Eastern)',
    'identity.timezone.london': 'UTC+0 (London)',
    'identity.timezone.europe': 'UTC+1 (Central Europe)',
    'identity.timezone.asia': 'UTC+8 (Asia)',
    'identity.timezone.japan': 'UTC+9 (Japan)',
    'identity.submit': 'Initialize Matrix',
    'identity.privacy': 'Your data is processed securely and never stored without consent',
    'identity.footer': 'Powered by advanced temporal logic engine',
    
    // Scenario Selection
    'scenario.title': 'Select Your Challenge',
    'scenario.subtitle': 'Choose the domain for strategic analysis',
    'scenario.investment.title': 'High-Stakes Investment',
    'scenario.investment.desc': 'Evaluate market entry, M&A, or portfolio rebalancing',
    'scenario.career.title': 'Career Transition',
    'scenario.career.desc': 'Job change, promotion negotiation, or entrepreneurship',
    'scenario.negotiation.title': 'Strategic Negotiation',
    'scenario.negotiation.desc': 'Contract signing, partnership, or conflict resolution',
    'scenario.timing.title': 'Critical Timing',
    'scenario.timing.desc': 'Project launch, relocation, or major life decision',
    'scenario.action': 'Analyze Strategy',
    'scenario.footer': 'Each analysis is uniquely calibrated to your temporal matrix',
    
    // The Inquiry
    'inquiry.title': 'The Inquiry',
    'inquiry.subtitle': 'Computing strategic pathways through the temporal matrix',
    'inquiry.analyzing': 'Analyzing',
    'inquiry.step1': 'Initializing temporal matrix...',
    'inquiry.step2': 'Calculating celestial coordinates...',
    'inquiry.step3': 'Mapping subject-object dynamics...',
    'inquiry.step4': 'Analyzing three transmissions path...',
    'inquiry.step5': 'Evaluating strategic variables...',
    'inquiry.step6': 'Synthesizing decision intelligence...',
    'inquiry.birthDate': 'Birth Date:',
    'inquiry.birthTime': 'Birth Time:',
    'inquiry.timezone': 'Timezone:',
    'inquiry.scenario': 'Scenario:',
    'inquiry.scenario.investment': 'investment',
    'inquiry.scenario.career': 'career',
    'inquiry.scenario.negotiation': 'negotiation',
    'inquiry.scenario.timing': 'timing',
    'inquiry.footer': 'Backend logic engine processing your unique temporal signature',
    
    // Strategy Dashboard
    'dashboard.title': 'Strategy Dashboard',
    'dashboard.subtitle.investment': 'Investment Analysis Complete',
    'dashboard.subtitle.career': 'Career Analysis Complete',
    'dashboard.subtitle.negotiation': 'Negotiation Analysis Complete',
    'dashboard.subtitle.timing': 'Timing Analysis Complete',
    'dashboard.efficiency': 'Efficiency Score',
    'dashboard.risk': 'Risk Index',
    'dashboard.evolution': 'Evolution Path',
    'dashboard.phase.initial': 'Initial',
    'dashboard.phase.middle': 'Middle',
    'dashboard.phase.final': 'Final',
    'dashboard.summary': 'Executive Summary',
    'dashboard.actions': 'Actionable Steps',
    'dashboard.newAnalysis': 'New Analysis',
    'dashboard.export': 'Export Report',
    'dashboard.footer': 'Strategic intelligence generated by temporal logic engine + AI synthesis',
    
    // Strategy Content (Investment)
    'strategy.investment.timeline.initial.status': 'Strong Growth Signal',
    'strategy.investment.timeline.initial.deity': 'Qing-Long (Capital)',
    'strategy.investment.timeline.middle.status': 'Competitive Pressure',
    'strategy.investment.timeline.middle.deity': 'Bai-Hu (Force)',
    'strategy.investment.timeline.final.status': 'Return to Growth',
    'strategy.investment.timeline.final.deity': 'Qing-Long (Capital)',
    'strategy.investment.summary': 'The temporal matrix indicates a favorable window for capital deployment. Initial momentum is strong, supported by positive market alignment. Mid-phase turbulence is expected due to competitive dynamics, but structural advantages position you for recovery.',
    'strategy.investment.action1': 'Execute entry within 72 hours to capture peak momentum',
    'strategy.investment.action2': 'Allocate 30% reserve for mid-phase volatility hedge',
    'strategy.investment.action3': 'Set profit-taking threshold at 85% efficiency score',
    'strategy.investment.action4': 'Monitor for competitive signal reversal in weeks 8-10',
    
    // Strategy Content (Career)
    'strategy.career.timeline.initial.status': 'Hidden Opportunity',
    'strategy.career.timeline.initial.deity': 'Tian-Kong (Void)',
    'strategy.career.timeline.middle.status': 'Power Alignment',
    'strategy.career.timeline.middle.deity': 'Gou-Chen (Authority)',
    'strategy.career.timeline.final.status': 'Stable Foundation',
    'strategy.career.timeline.final.deity': 'Teng-She (Structure)',
    'strategy.career.summary': 'Career transition shows moderate strategic advantage with patience required. Initial phase reveals non-obvious opportunities requiring deeper exploration. Authority alignment emerges mid-cycle, creating negotiation leverage.',
    'strategy.career.action1': 'Research 3-5 unconventional pathways before committing',
    'strategy.career.action2': 'Schedule critical conversations during weeks 4-6',
    'strategy.career.action3': 'Document achievements for leverage in negotiations',
    'strategy.career.action4': 'Build strategic relationships with decision-makers',
    
    // Strategy Content (Negotiation)
    'strategy.negotiation.timeline.initial.status': 'Mutual Benefit Signal',
    'strategy.negotiation.timeline.initial.deity': 'Tai-Yin (Harmony)',
    'strategy.negotiation.timeline.middle.status': 'Strategic Clarity',
    'strategy.negotiation.timeline.middle.deity': 'Tian-Hou (Nobility)',
    'strategy.negotiation.timeline.final.status': 'Sustainable Win-Win',
    'strategy.negotiation.timeline.final.deity': 'Liu-He (Alliance)',
    'strategy.negotiation.summary': 'Negotiation matrix shows exceptional alignment for mutually beneficial outcomes. Harmony indicators suggest counterparty shares strategic interests. High probability of sustainable partnership formation.',
    'strategy.negotiation.action1': 'Lead with collaborative framing in opening statements',
    'strategy.negotiation.action2': 'Propose tiered value-exchange structure',
    'strategy.negotiation.action3': 'Schedule final agreement signing within 10-day window',
    'strategy.negotiation.action4': 'Build long-term relationship mechanisms into contract',
    
    // Strategy Content (Timing)
    'strategy.timing.timeline.initial.status': 'Premature Launch Risk',
    'strategy.timing.timeline.initial.deity': 'Zhu-Que (Speed)',
    'strategy.timing.timeline.middle.status': 'Resource Consolidation',
    'strategy.timing.timeline.middle.deity': 'Gou-Chen (Control)',
    'strategy.timing.timeline.final.status': 'Optimal Execution Window',
    'strategy.timing.timeline.final.deity': 'Qing-Long (Success)',
    'strategy.timing.summary': 'Timing analysis reveals patience will yield superior outcomes. Initial impulse to act should be resisted. Mid-phase requires resource preparation and stakeholder alignment before final execution window opens.',
    'strategy.timing.action1': 'Delay launch by 2-3 weeks from original plan',
    'strategy.timing.action2': 'Use initial phase for stress-testing and preparation',
    'strategy.timing.action3': 'Consolidate resources and team alignment mid-cycle',
    'strategy.timing.action4': 'Execute during final window for maximum impact',
  },
  zh: {
    // Common
    'app.title': '人生策略AI',
    'app.subtitle': '关键决策的战略智能',
    
    // Identity Sync
    'identity.title': '人生策略AI',
    'identity.subtitle': '为关键决策提供战略智能',
    'identity.heading': '身份同步',
    'identity.description': '您的时间坐标将解锁战略矩阵',
    'identity.birthDate': '出生日期',
    'identity.birthTime': '出生时间',
    'identity.timezone': '时区',
    'identity.timezone.pacific': 'UTC-8 (太平洋时区)',
    'identity.timezone.eastern': 'UTC-5 (东部时区)',
    'identity.timezone.london': 'UTC+0 (伦敦)',
    'identity.timezone.europe': 'UTC+1 (中欧)',
    'identity.timezone.asia': 'UTC+8 (亚洲)',
    'identity.timezone.japan': 'UTC+9 (日本)',
    'identity.submit': '初始化矩阵',
    'identity.privacy': '您的数据经过安全处理，未经同意绝不存储',
    'identity.footer': '由先进的时间逻辑引擎驱动',
    
    // Scenario Selection
    'scenario.title': '选择您的挑战',
    'scenario.subtitle': '选择战略分析领域',
    'scenario.investment.title': '高风险投资',
    'scenario.investment.desc': '评估市场进入、并购或投资组合调整',
    'scenario.career.title': '职业转型',
    'scenario.career.desc': '工作变动、晋升谈判或创业',
    'scenario.negotiation.title': '战略谈判',
    'scenario.negotiation.desc': '合同签署、合作伙伴关系或冲突解决',
    'scenario.timing.title': '关键时机',
    'scenario.timing.desc': '项目启动、搬迁或重大人生决策',
    'scenario.action': '分析策略',
    'scenario.footer': '每次分析都根据您的时间矩阵进行独特校准',
    
    // The Inquiry
    'inquiry.title': '策略推演',
    'inquiry.subtitle': '通过时间矩阵计算战略路径',
    'inquiry.analyzing': '分析中',
    'inquiry.step1': '初始化时间矩阵...',
    'inquiry.step2': '计算天体坐标...',
    'inquiry.step3': '映射主客体动态...',
    'inquiry.step4': '分析三传路径...',
    'inquiry.step5': '评估战略变量...',
    'inquiry.step6': '综合决策智能...',
    'inquiry.birthDate': '出生日期：',
    'inquiry.birthTime': '出生时间：',
    'inquiry.timezone': '时区：',
    'inquiry.scenario': '场景：',
    'inquiry.scenario.investment': '投资',
    'inquiry.scenario.career': '职业',
    'inquiry.scenario.negotiation': '谈判',
    'inquiry.scenario.timing': '时机',
    'inquiry.footer': '后端逻辑引擎正在处理您的独特时间签名',
    
    // Strategy Dashboard
    'dashboard.title': '策略仪表板',
    'dashboard.subtitle.investment': '投资分析完成',
    'dashboard.subtitle.career': '职业分析完成',
    'dashboard.subtitle.negotiation': '谈判分析完成',
    'dashboard.subtitle.timing': '时机分析完成',
    'dashboard.efficiency': '效率评分',
    'dashboard.risk': '风险指数',
    'dashboard.evolution': '演化路径',
    'dashboard.phase.initial': '初期',
    'dashboard.phase.middle': '中期',
    'dashboard.phase.final': '末期',
    'dashboard.summary': '执行摘要',
    'dashboard.actions': '可执行步骤',
    'dashboard.newAnalysis': '新分析',
    'dashboard.export': '导出报告',
    'dashboard.footer': '由时间逻辑引擎 + AI综合生成的战略智能',
    
    // Strategy Content (Investment)
    'strategy.investment.timeline.initial.status': '强劲增长信号',
    'strategy.investment.timeline.initial.deity': '青龙（资本）',
    'strategy.investment.timeline.middle.status': '竞争压力',
    'strategy.investment.timeline.middle.deity': '白虎（力量）',
    'strategy.investment.timeline.final.status': '回归增长',
    'strategy.investment.timeline.final.deity': '青龙（资本）',
    'strategy.investment.summary': '时间矩阵显示资本部署的有利窗口。初期势头强劲，得到积极的市场协调支持。由于竞争动态，预计中期会出现动荡，但结构性优势使您能够恢复。',
    'strategy.investment.action1': '在72小时内执行入场以捕捉峰值动量',
    'strategy.investment.action2': '分配30%储备金用于中期波动对冲',
    'strategy.investment.action3': '将获利门槛设定在85%效率评分',
    'strategy.investment.action4': '监控第8-10周的竞争信号反转',
    
    // Strategy Content (Career)
    'strategy.career.timeline.initial.status': '隐藏机会',
    'strategy.career.timeline.initial.deity': '天空（虚空）',
    'strategy.career.timeline.middle.status': '权力协调',
    'strategy.career.timeline.middle.deity': '勾陈（权威）',
    'strategy.career.timeline.final.status': '稳定基础',
    'strategy.career.timeline.final.deity': '螣蛇（结构）',
    'strategy.career.summary': '职业转型显示出适度的战略优势，需要耐心。初期阶段揭示了需要深入探索的非显而易见的机会。权威协调在中期出现，创造谈判杠杆。',
    'strategy.career.action1': '在承诺之前研究3-5条非常规路径',
    'strategy.career.action2': '在第4-6周安排关键对话',
    'strategy.career.action3': '记录成就以在谈判中获得杠杆',
    'strategy.career.action4': '与决策者建立战略关系',
    
    // Strategy Content (Negotiation)
    'strategy.negotiation.timeline.initial.status': '互惠信号',
    'strategy.negotiation.timeline.initial.deity': '太阴（和谐）',
    'strategy.negotiation.timeline.middle.status': '战略清晰',
    'strategy.negotiation.timeline.middle.deity': '天后（高贵）',
    'strategy.negotiation.timeline.final.status': '可持续双赢',
    'strategy.negotiation.timeline.final.deity': '六合（联盟）',
    'strategy.negotiation.summary': '谈判矩阵显示互惠结果的卓越协调。和谐指标表明对方共享战略利益。形成可持续伙伴关系的高概率。',
    'strategy.negotiation.action1': '在开场陈述中以协作框架为主导',
    'strategy.negotiation.action2': '提出分层价值交换结构',
    'strategy.negotiation.action3': '在10天窗口内安排最终协议签署',
    'strategy.negotiation.action4': '在合同中建立长期关系机制',
    
    // Strategy Content (Timing)
    'strategy.timing.timeline.initial.status': '过早启动风险',
    'strategy.timing.timeline.initial.deity': '朱雀（速度）',
    'strategy.timing.timeline.middle.status': '资源整合',
    'strategy.timing.timeline.middle.deity': '勾陈（控制）',
    'strategy.timing.timeline.final.status': '最佳执行窗口',
    'strategy.timing.timeline.final.deity': '青龙（成功）',
    'strategy.timing.summary': '时机分析表明耐心将产生更优结果。应该抵制最初的行动冲动。中期需要资源准备和利益相关者协调，然后最终执行窗口打开。',
    'strategy.timing.action1': '从原计划延迟2-3周启动',
    'strategy.timing.action2': '利用初期阶段进行压力测试和准备',
    'strategy.timing.action3': '在中期整合资源和团队协调',
    'strategy.timing.action4': '在最终窗口执行以获得最大影响',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
